### ISSUE TITLE
Redshift error

### ISSUE THREAD

**Issue by codeinzen** [embulk/embulk-output-jdbc#106]
Hi 

I am doing a bulk upload into redshift. By the looks of it the data is getting copied into S3 from a simple select \* statement in mysql. 

However I am getting a postgresql error when uploading into redshift. 

```
Java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 22

 Position: 22
        at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$PluginPageOutput.finish(AbstractJdbcOutputPlugin.java:910)
        at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput.finish(LocalExecutorPlugin.java:496)
        at org.embulk.spi.PageBuilder.finish(PageBuilder.java:244)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.run(AbstractJdbcInputPlugin.java:279)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:294)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$000(LocalExecutorPlugin.java:212)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:257)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:253)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 22
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:481)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:409)
        at org.embulk.output.redshift.RedshiftOutputConnection.runCopy(RedshiftOutputConnection.java:117)
        at org.embulk.output.redshift.RedshiftCopyBatchInsert$CopyTask.call(RedshiftCopyBatchInsert.java:242)
        at org.embulk.output.redshift.RedshiftCopyBatchInsert$CopyTask.call(RedshiftCopyBatchInsert.java:218)
```

**Comment by hito4t** [comment]
Hi
Column names in yml are case sensitive.
(I am planning to fix this problem. https://github.com/embulk/embulk-output-jdbc/issues/97)

If column names in yml are upper case letters, embulk-output-redshift cannot find the columns in the output table because redshift column names are lower case letters, and builds illegal SQL (COPY statement with no columns).
