### ISSUE TITLE
MySQLSyntaxErrorException: Invalid default value 

### ISSUE THREAD

**Issue by koooge** [embulk/embulk-output-jdbc#171]
Hello.
I use MYSQL:5.7 and found error.

```

017-05-11 19:20:14.742 +0900 [INFO] (0001:transaction): SQL: CREATE TABLE IF NOT EXISTS `table_0000000059143ade13e86f80_bl_tmp000` (`column_name` TIMESTAMP ...) at org.jruby.RubyKernel.require19(RubyKernel.java:956)

...

Error: java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Invalid default value for 'column_name'
        at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.begin(AbstractJdbcOutputPlugin.java:397)
        at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.transaction(AbstractJdbcOutputPlugin.java:354)
        at org.embulk.exec.BulkLoader$4$1$1.transaction(BulkLoader.java:544)
        at org.embulk.exec.LocalExecutorPlugin.transaction(LocalExecutorPlugin.java:54)
        at org.embulk.exec.BulkLoader$4$1.run(BulkLoader.java:539)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:96)
        at org.embulk.spi.util.Filters.transaction(Filters.java:49)
        at org.embulk.exec.BulkLoader$4.run(BulkLoader.java:533)
...
```

I think `explicit_defaults_for_timestamp` could be related.
cf. https://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html
Is there ways to set default value? Or do you have workarouds? :confounded:

**Comment by hito4t** [comment]
Hello.
Thank you for writing the issue!

As you wrote, `explicit_defaults_for_timestamp` may be one of the causes.
I found that the problem occurs in the following conditions.
- explicit_defaults_for_timestamp = false
- multiple timestamp columns (default value of the second timestamp column will be set to 0 automatically)
- sql_mode=NO_ZERO_DATE (error if timestamp value is 0)
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date

If you can set `explicit_defaults_for_timestamp` to true or remove `NO_ZERO_DATE` from `sql_mode`, the exception won't be thrown.

**Comment by hito4t** [comment]
@koooge 
or you can specify column type by `type` of `column_options`.

<pre>
out:
  type: mysql
  ...
  column_options:
    column_name: {type: 'timestamp default current_timestamp'}
</pre>

**Comment by koooge** [comment]
@hito4t 
I think `explicit_defaults_for_timestamp = faluse` is deplicated.
So I tried to use *column_options*. But it seems not to be working correctly.
Thank you! :+1: :+1:
