### ISSUE TITLE
False alert I/O error when transfer large csv file from GCS to postgres

### ISSUE THREAD

**Issue by Patrick-Shih** [embulk/embulk-output-jdbc#185]
Hi there,

I encountered a strange false alert I/O error when transfer large csv file from google cloud storage to postgres db.  This false alert does not harm current task, but prevent subsequent task to be executed.

`org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.`

Here is what stdout shows...
```
2017-07-10 00:01:44.910 +0000: Embulk v0.8.15
2017-07-10 00:01:52.908 +0000 [INFO] (0001:transaction): Loaded plugin embulk-input-gcs (0.2.3)
2017-07-10 00:01:53.182 +0000 [INFO] (0001:transaction): Loaded plugin embulk-output-postgresql (0.7.1)
2017-07-10 00:01:55.345 +0000 [INFO] (0001:transaction): Using local thread executor with max_threads=2 / tasks=1
2017-07-10 00:01:55.438 +0000 [INFO] (0001:transaction): Connecting to jdbc:postgresql://my.test.site:5432/postgres options {user=postgres, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2017-07-10 00:01:55.683 +0000 [INFO] (0001:transaction): SQL: SET search_path TO "public"
2017-07-10 00:01:55.688 +0000 [INFO] (0001:transaction): > 0.00 seconds
2017-07-10 00:01:55.690 +0000 [INFO] (0001:transaction): Using merge mode
2017-07-10 00:01:55.754 +0000 [INFO] (0001:transaction): SQL: DROP TABLE IF EXISTS "my_table_1443fd00_bl_tmp000"
2017-07-10 00:01:55.761 +0000 [INFO] (0001:transaction): > 0.00 seconds
2017-07-10 00:01:55.818 +0000 [INFO] (0001:transaction): SQL: CREATE TABLE IF NOT EXISTS "my_table_1443fd00_bl_tmp000" ("pkey" INT8, "appkey" VARCHAR(255), "timestamp" TIMESTAMPTZ)
2017-07-10 00:01:55.834 +0000 [INFO] (0001:transaction): > 0.01 seconds
2017-07-10 00:01:55.875 +0000 [INFO] (0001:transaction): Using merge keys: [pkey]
2017-07-10 00:01:55.975 +0000 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2017-07-10 00:01:56.081 +0000 [INFO] (0018:task-0000): Connecting to jdbc:postgresql://my.test.site:5432/postgres options {user=postgres, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2017-07-10 00:01:56.123 +0000 [INFO] (0018:task-0000): SQL: SET search_path TO "public"
2017-07-10 00:01:56.125 +0000 [INFO] (0018:task-0000): > 0.00 seconds
2017-07-10 00:01:56.126 +0000 [INFO] (0018:task-0000): Copy SQL: COPY "my_table_1443fd00_bl_tmp000" ("pkey", "appkey", "timestamp") FROM STDIN
2017-07-10 00:02:24.718 +0000 [INFO] (0018:task-0000): Loading 76,950 rows (16,838,450 bytes)
2017-07-10 00:02:25.239 +0000 [INFO] (0018:task-0000): > 0.52 seconds (loaded 76,950 rows in total)
2017-07-10 00:02:43.184 +0000 [INFO] (0018:task-0000): Loading 76,933 rows (16,800,376 bytes)
2017-07-10 00:02:43.626 +0000 [INFO] (0018:task-0000): > 0.44 seconds (loaded 153,883 rows in total)
2017-07-10 00:03:00.670 +0000 [INFO] (0018:task-0000): Loading 76,936 rows (16,801,437 bytes)
2017-07-10 00:03:01.205 +0000 [INFO] (0018:task-0000): > 0.53 seconds (loaded 230,819 rows in total)
2017-07-10 00:03:16.362 +0000 [INFO] (0018:task-0000): Loading 74,287 rows (16,829,979 bytes)
2017-07-10 00:03:16.881 +0000 [INFO] (0018:task-0000): > 0.52 seconds (loaded 305,106 rows in total)
2017-07-10 00:03:31.760 +0000 [INFO] (0018:task-0000): Loading 66,121 rows (16,823,380 bytes)
2017-07-10 00:03:32.299 +0000 [INFO] (0018:task-0000): > 0.54 seconds (loaded 371,227 rows in total)
2017-07-10 00:03:46.603 +0000 [INFO] (0018:task-0000): Loading 66,145 rows (16,832,419 bytes)
2017-07-10 00:03:47.609 +0000 [INFO] (0018:task-0000): > 1.01 seconds (loaded 437,372 rows in total)
2017-07-10 00:04:01.626 +0000 [INFO] (0018:task-0000): Loading 66,157 rows (16,829,976 bytes)
2017-07-10 00:04:02.157 +0000 [INFO] (0018:task-0000): > 0.53 seconds (loaded 503,529 rows in total)
2017-07-10 00:04:17.086 +0000 [INFO] (0018:task-0000): Loading 66,152 rows (16,831,553 bytes)
2017-07-10 00:04:17.624 +0000 [INFO] (0018:task-0000): > 0.53 seconds (loaded 569,681 rows in total)
2017-07-10 00:04:32.413 +0000 [INFO] (0018:task-0000): Loading 66,005 rows (16,794,649 bytes)
2017-07-10 00:04:34.041 +0000 [INFO] (0018:task-0000): > 1.63 seconds (loaded 635,686 rows in total)
2017-07-10 00:04:49.160 +0000 [INFO] (0018:task-0000): Loading 66,117 rows (16,821,236 bytes)
2017-07-10 00:04:49.644 +0000 [INFO] (0018:task-0000): > 0.48 seconds (loaded 701,803 rows in total)
2017-07-10 00:05:04.432 +0000 [INFO] (0018:task-0000): Loading 72,576 rows (16,838,571 bytes)
2017-07-10 00:05:04.963 +0000 [INFO] (0018:task-0000): > 0.53 seconds (loaded 774,379 rows in total)
2017-07-10 00:05:21.505 +0000 [INFO] (0018:task-0000): Loading 76,937 rows (16,801,629 bytes)
2017-07-10 00:05:22.007 +0000 [INFO] (0018:task-0000): > 0.50 seconds (loaded 851,316 rows in total)
2017-07-10 00:05:26.841 +0000 [INFO] (0018:task-0000): Loading 23,062 rows (5,036,427 bytes)
2017-07-10 00:05:26.970 +0000 [INFO] (0018:task-0000): > 0.13 seconds (loaded 874,378 rows in total)
2017-07-10 00:05:26.974 +0000 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2017-07-10 00:05:26.975 +0000 [INFO] (0001:transaction): Connecting to jdbc:postgresql://my.test.site:5432/postgres options {user=postgres, tcpKeepAlive=true, loginTimeout=300, socketTimeout=28800}
2017-07-10 00:05:27.004 +0000 [INFO] (0001:transaction): SQL: SET search_path TO "public"
2017-07-10 00:05:27.007 +0000 [INFO] (0001:transaction): > 0.00 seconds
2017-07-10 00:05:27.008 +0000 [INFO] (0001:transaction): SQL: WITH updated AS (UPDATE "my_table" SET "pkey" = S."pkey", "appkey" = S."appkey", "timestamp" = S."timestamp" FROM (SELECT "pkey", "appkey", "timestamp" FROM "my_table_1443fd00_bl_tmp000") S WHERE "my_table"."pkey" = S."pkey" RETURNING S."pkey") INSERT INTO "my_table" ("pkey", "appkey", "timestamp") SELECT DISTINCT ON ("pkey") * FROM (SELECT "pkey", "appkey", "timestamp" FROM "my_table_1443fd00_bl_tmp000") S WHERE NOT EXISTS (SELECT 1 FROM updated WHERE S."pkey" = updated."pkey") 
2017-07-10 02:05:43.901 +0000 [ERROR] (0001:transaction): Operation failed (0:08006)
2017-07-10 02:05:43.922 +0000 [INFO] (0001:cleanup): Connecting to jdbc:postgresql://my.test.site:5432/postgres options {user=postgres, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2017-07-10 02:05:43.939 +0000 [INFO] (0001:cleanup): SQL: SET search_path TO "public"
2017-07-10 02:05:43.940 +0000 [INFO] (0001:cleanup): > 0.00 seconds
2017-07-10 02:05:43.941 +0000 [INFO] (0001:cleanup): SQL: DROP TABLE IF EXISTS "my_table_1443fd00_bl_tmp000"
2017-07-10 02:05:43.962 +0000 [INFO] (0001:cleanup): > 0.02 seconds
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
...
<The full stacktrace provided at the end>
...
```
One can found that between the "WITH updated AS" sql statement and the ERROR it elapsed around 2 hours (00:05:27 -> 02:05:43).

And here is the related postgres log for the updata statement
```
2017-07-10 00:05:27 UTC [postgres:25599] - LOG:  connection authorized: user=postgres database=postgres
2017-07-10 00:05:27 UTC [postgres:25599] - LOG:  execute <unnamed>: WITH updated AS (UPDATE "my_table" SET "pkey" = S."pkey", "appkey" = S."appkey", "timestamp" = S."timestamp" FROM (SELECT "pkey", "appkey", "timestamp" FROM "my_table_1443fd00_bl_tmp000") S WHERE "my_table"."pkey" = S."pkey" RETURNING S."pkey") INSERT INTO "my_table" ("pkey", "appkey", "timestamp") SELECT DISTINCT ON ("pkey") * FROM (SELECT "pkey", "appkey", "timestamp" FROM "my_table_1443fd00_bl_tmp000") S WHERE NOT EXISTS (SELECT 1 FROM updated WHERE S."pkey" = updated."pkey") 
2017-07-10 00:15:49 UTC [postgres:25599] - LOG:  duration: 621493.201 ms
2017-07-10 00:15:52 UTC [postgres:25599] - LOG:  duration: 632.396 ms  execute S_1: COMMIT
2017-07-10 00:15:52 UTC [postgres:25599] - LOG:  disconnection: session time: 0:09:26.186 user=postgres database=postgres host=my.test.site port=40422
```

It is strange that there is no error in postgres, the update statement complete in around 10 min!  It looks to me that the embulk or something in the middle does not catch up the finish event and keep waiting until some timeout mechanism occurs after 2 hours.

I also tested with various sql execution time (by changing csv file size) and found out it is related.  When sql execution time exceed around 600s the I/O error occurs, for time smaller than that it executed perfectly.

The X means I/O Error occurs
```
SQL execution time (second)  Status
	507			O
	553			O
	611			O
	597			O
	631			X
	646			X
	684			X
	676			X
	636			X
```

Embulk config yaml
```
in:
  type: gcs
  auth_method: compute_engine
  bucket: [omitted for security]
  path_prefix: [omitted for security]
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: pkey, type: long}
    - {name: appKey, type: string}
    - {name: timestamp, type: timestamp, format: '%Y-%m-%d %H:%M:%S %z'}
out:
  type: postgresql
  host: [omitted for security]
  user: postgres
  password: [omitted for security]
  database: postgres
  table: my_table
  mode: merge
  merge_keys: [pkey]
```

Full stack trace...
```
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:373)
	at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:591)
	at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:389)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:385)
	at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
	at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:385)
	at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:180)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:453)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:314)
	at RUBY.run(/usr/local/bin/embulk!/embulk/runner.rb:84)
	at RUBY.run(/usr/local/bin/embulk!/embulk/command/embulk_run.rb:307)
	at RUBY.<main>(/usr/local/bin/embulk!/embulk/command/embulk_main.rb:2)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:850)
	at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2976)
	at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:963)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
	at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
	at usr.local.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(usr/local/bin/embulk/embulk/command/file:/usr/local/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at usr.local.bin.embulk.embulk.command.embulk_bundle.<main>(file:/usr/local/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)
	at org.jruby.Ruby.runScript(org/jruby/Ruby.java:834)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:749)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:767)
	at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:580)
	at org.jruby.Main.doRunFromMain(org/jruby/Main.java:425)
	at org.jruby.Main.internalRun(org/jruby/Main.java:313)
	at org.jruby.Main.run(org/jruby/Main.java:242)
	at org.jruby.Main.main(org/jruby/Main.java:204)
	at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
Caused by: java.lang.RuntimeException: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.commit(AbstractJdbcOutputPlugin.java:415)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.transaction(AbstractJdbcOutputPlugin.java:352)
	at org.embulk.exec.BulkLoader$4$1$1.transaction(BulkLoader.java:544)
	at org.embulk.exec.LocalExecutorPlugin.transaction(LocalExecutorPlugin.java:54)
	at org.embulk.exec.BulkLoader$4$1.run(BulkLoader.java:539)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:96)
	at org.embulk.spi.util.Filters.transaction(Filters.java:49)
	at org.embulk.exec.BulkLoader$4.run(BulkLoader.java:533)
	at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(FileInputRunner.java:123)
	at org.embulk.standards.CsvParserPlugin.transaction(CsvParserPlugin.java:225)
	at org.embulk.spi.FileInputRunner$RunnerControl$1.run(FileInputRunner.java:117)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:77)
	at org.embulk.spi.util.Decoders.transaction(Decoders.java:33)
	at org.embulk.spi.FileInputRunner$RunnerControl.run(FileInputRunner.java:114)
	at org.embulk.input.gcs.GcsFileInputPlugin.resume(GcsFileInputPlugin.java:181)
	at org.embulk.input.gcs.GcsFileInputPlugin.transaction(GcsFileInputPlugin.java:155)
	at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:65)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:528)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:33)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:389)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:385)
	at org.embulk.spi.Exec.doWith(Exec.java:25)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:385)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:453)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:314)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:46)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:205)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:358)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:195)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35)
	at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
	at org.jruby.Ruby.runInterpreter(Ruby.java:850)
	at org.jruby.Ruby.loadFile(Ruby.java:2976)
	at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:243)
	at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34)
	at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:885)
	at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:525)
	at org.jruby.runtime.load.LoadService.require(LoadService.java:396)
	at org.jruby.RubyKernel.requireCommon(RubyKernel.java:963)
	at org.jruby.RubyKernel.require19(RubyKernel.java:956)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:383)
	at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at usr.local.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(file:/usr/local/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at usr.local.bin.embulk.embulk.command.embulk_bundle.RUBY$script(file:/usr/local/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.jruby.ir.Compiler$1.load(Compiler.java:111)
	at org.jruby.Ruby.runScript(Ruby.java:834)
	at org.jruby.Ruby.runNormally(Ruby.java:749)
	at org.jruby.Ruby.runNormally(Ruby.java:767)
	at org.jruby.Ruby.runFromMain(Ruby.java:580)
	at org.jruby.Main.doRunFromMain(Main.java:425)
	at org.jruby.Main.internalRun(Main.java:313)
	at org.jruby.Main.run(Main.java:242)
	at org.jruby.Main.main(Main.java:204)
	at org.embulk.cli.Main.main(Main.java:23)
Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:201)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:481)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:409)
	at org.embulk.output.jdbc.JdbcOutputConnection.executeUpdate(JdbcOutputConnection.java:497)
	at org.embulk.output.jdbc.JdbcOutputConnection.collectMerge(JdbcOutputConnection.java:368)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.doCommit(AbstractJdbcOutputPlugin.java:705)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$2.run(AbstractJdbcOutputPlugin.java:408)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$RetryableSQLExecution.call(AbstractJdbcOutputPlugin.java:1074)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$RetryableSQLExecution.call(AbstractJdbcOutputPlugin.java:1062)
	at org.embulk.spi.util.RetryExecutor.run(RetryExecutor.java:100)
	at org.embulk.spi.util.RetryExecutor.runInterruptible(RetryExecutor.java:77)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.withRetry(AbstractJdbcOutputPlugin.java:1046)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.withRetry(AbstractJdbcOutputPlugin.java:1039)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.commit(AbstractJdbcOutputPlugin.java:403)
	... 88 more
	Suppressed: org.postgresql.util.PSQLException: This connection has been closed.
		at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:853)
		at org.postgresql.jdbc2.AbstractJdbc2Connection.getAutoCommit(AbstractJdbc2Connection.java:814)
		at org.embulk.output.jdbc.JdbcOutputConnection.safeRollback(JdbcOutputConnection.java:517)
		at org.embulk.output.jdbc.JdbcOutputConnection.collectMerge(JdbcOutputConnection.java:374)
		... 97 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:143)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:112)
	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:71)
	at org.postgresql.core.PGStream.ReceiveChar(PGStream.java:282)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1718)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	... 102 more
```

**Comment by hito4t** [comment]
Hi,

PostgreSQL JDBC Driver has `socketTimeout` property, but the above log shows it was 28800s (not 600s).
And PostgreSQL  Server Configuration has `statement_timeout` property, but it would raise a different error (I've tested).

Is there some another timeout between the client and the PostgreSQL server?
(ex. network timeout)

**Comment by Patrick-Shih** [comment]
I don't think so.  If there is some other timeout I "guess" embulk should also raise some sort of exception respectively and show some error immediate instead of 2 hours later.

However, I am not expert of postgres.  If you require more info to diagnostic, I would be happy to provide ^_^

**Comment by hito4t** [comment]
embulk-output-postgresql simply catches an exception thrown by PostgreSQL JDBC Driver.
But we can't know what happened in the JDBC Driver by the above log.

I made the JAR file to output JDBC Driver debug log.
(we can't do by yml...)
https://github.com/embulk/embulk-output-jdbc/blob/postgresql_logging_v0_7_1/jar/embulk-output-postgresql-0.7.1-logging.jar

Would you download the JAR file, replace it with `<home>/.embulk/jruby/2.3.0/gems/embulk-output-postgresql-0.7.1/classpath/embulk-output-postgresql-0.7.1.jar` and retry?

**Comment by Patrick-Shih** [comment]
Sure, I will update once I got the result.
