### ISSUE TITLE
0.7.11 Fails with embulk 0.8.29

### ISSUE THREAD

**Issue by kakoni** [embulk/embulk-output-jdbc#202]
Using embulk-output-postgresql

Getting this error
```
org.embulk.exec.PartialExecutionException: org.embulk.config.ConfigException: com.fasterxml.jackson.databind.JsonMappingException: Setting null to a task field is not allowed. Use Optional<T> (com.google.common.base.Optional) to represent null.                                        
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:375)                                                 
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:607)                                                                
        at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)                                                    
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:391)                                        
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:387)                                            
        at org.embulk.spi.Exec.doWith(Exec.java:25)                                                        
        at org.embulk.exec.BulkLoader.run(BulkLoader.java:387)                                                                                                                   
        at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:180)                                                                   
        at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:330)                                   
        at org.embulk.EmbulkRunner.run(EmbulkRunner.java:173)                                           
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:472)                                                             
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:100)                                             
        at org.embulk.cli.EmbulkBundle.checkBundleWithEmbulkVersion(EmbulkBundle.java:42)                 
        at org.embulk.cli.EmbulkBundle.checkBundle(EmbulkBundle.java:15)                                
        at org.embulk.cli.Main.main(Main.java:26)                                                                       
        Suppressed: java.lang.NullPointerException                                                            
                at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:496)                                       
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:427)                                                                                  
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:423)                           
                at org.embulk.spi.Exec.doWith(Exec.java:25)                                                             
                at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:423)                                    
                at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:184) 

```

**Comment by hiroyuki-sato** [comment]
Hello, @kakoni 

* Can you try it with embulk 0.8.35?
* If it causes same error, Is it possible to provide us your configuration and data?

**Comment by kakoni** [comment]
Sure (0.8.29 was were I first started encountering this). 
Anyway, here are the results with 0.8.35

embulk conf
```yaml
in:
  type: file
  path_prefix: test_data/test.csv
  parser:
    type: csv
    skip_header_lines: 1
    columns:
      - {name: a, type: string}
      - {name: b, type: string}
      - {name: c, type: string}
out:
  type: postgresql
  host: {{ env.HOST }}
  user: {{ env.USER }}
  password: {{ env.PASSWORD }}
  port: {{ env.PORT }}
  database: {{ env.DATABASE }}
  table: embulk_test
```

result from the run
```
2017-09-29 21:16:27.101 +0300: Embulk v0.8.35                                                                                                                                    
2017-09-29 21:16:34.265 +0300 [INFO] (0001:transaction): Loaded plugin embulk-output-postgresql (0.7.11)
2017-09-29 21:16:34.297 +0300 [INFO] (0001:transaction): Listing local files at directory 'test_data' filtering filename by prefix 'test.csv'
2017-09-29 21:16:34.298 +0300 [INFO] (0001:transaction): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2017-09-29 21:16:34.305 +0300 [INFO] (0001:transaction): Loading files [test_data/test.csv]                                                                                      2017-09-29 21:16:34.369 +0300 [INFO] (0001:transaction): Using local thread executor with max_threads=16 / output tasks 8 = input tasks 1 * 8
org.embulk.exec.PartialExecutionException: org.embulk.config.ConfigException: com.fasterxml.jackson.databind.JsonMappingException: Setting null to a task field is not allowed. Use Optional<T> (com.google.common.base.Optional) to represent null.
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:375)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:607)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:391)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:387)
	at org.embulk.spi.Exec.doWith(Exec.java:25)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:387)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:180)
	at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:337)
	at org.embulk.EmbulkRunner.run(EmbulkRunner.java:174)
	at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:467)
	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:99)
	at org.embulk.cli.Main.main(Main.java:28)
	Suppressed: java.lang.NullPointerException
		at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:496)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:427)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:423)
		at org.embulk.spi.Exec.doWith(Exec.java:25)
		at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:423)
		at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:184)
		... 5 more
Caused by: org.embulk.config.ConfigException: com.fasterxml.jackson.databind.JsonMappingException: Setting null to a task field is not allowed. Use Optional<T> (com.google.common.base.Optional) to represent null.
	at org.embulk.config.ModelManager.readObjectWithConfigSerDe(ModelManager.java:75)
	at org.embulk.config.DataSourceImpl.loadConfig(DataSourceImpl.java:220)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.transaction(AbstractJdbcOutputPlugin.java:347)
	at org.embulk.exec.BulkLoader$4$1$1.transaction(BulkLoader.java:560)
	at org.embulk.exec.LocalExecutorPlugin.transaction(LocalExecutorPlugin.java:54)
	at org.embulk.exec.BulkLoader$4$1.run(BulkLoader.java:555)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:96)
	at org.embulk.spi.util.Filters.transaction(Filters.java:49)
	at org.embulk.exec.BulkLoader$4.run(BulkLoader.java:549)
	at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(FileInputRunner.java:126)
	at org.embulk.standards.CsvParserPlugin.transaction(CsvParserPlugin.java:225)
	at org.embulk.spi.FileInputRunner$RunnerControl$1.run(FileInputRunner.java:120)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:77)
	at org.embulk.spi.util.Decoders.transaction(Decoders.java:33)
	at org.embulk.spi.FileInputRunner$RunnerControl.run(FileInputRunner.java:117)
	at org.embulk.standards.LocalFileInputPlugin.resume(LocalFileInputPlugin.java:87)
	at org.embulk.standards.LocalFileInputPlugin.transaction(LocalFileInputPlugin.java:77)
	at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:67)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:544)
	... 11 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Setting null to a task field is not allowed. Use Optional<T> (com.google.common.base.Optional) to represent null.
	at org.embulk.config.TaskSerDe$TaskDeserializer.deserialize(TaskSerDe.java:163)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3708)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2005)
	at org.embulk.config.ModelManager.readObjectWithConfigSerDe(ModelManager.java:72)
	... 29 more

Error: org.embulk.config.ConfigException: com.fasterxml.jackson.databind.JsonMappingException: Setting null to a task field is not allowed. Use Optional<T> (com.google.common.base.Optional) to represent null.
```

**Comment by hiroyuki-sato** [comment]
Hello, @kakoni 

Can you try the following?
* Add `mode` configuration [sample](https://github.com/hiroyuki-sato/embulk-support/blob/master/input-jdbc_202-pg_test/conf.yml.liquid#L19)
* Have you ever checked target table exists or not?
* Use `yml.liquid` suffix instead of `yml`.

It seems work on my environment.
https://github.com/hiroyuki-sato/embulk-support/tree/master/input-jdbc_202-pg_test

* embulk 0.8.35
* embulk-output-postgresql: 0.7.11

**Comment by kakoni** [comment]
Sorry, just realized this was bug in dotenv, not this plugin. 
Related; https://github.com/embulk/embulk/issues/778

Closing this.
