### ISSUE TITLE
Invalid INSERT INTO statement is executed when no record exists

### ISSUE THREAD

**Issue by muziyoshiz** [embulk/embulk-output-jdbc#51]
If file input plugin does not read any record because of last_path parameter, postgresql output plugin (and maybe other plugins using jdbc plugin) throws following exception.

```
jarvis% embulk run psql-test-config.yml
2015-07-02 18:45:14.624 +0900: Embulk v0.6.16
2015-07-02 18:45:17.163 +0900 [INFO] (transaction): Loaded plugin embulk-output-postgresql (0.3.0)
2015-07-02 18:45:17.244 +0900 [INFO] (transaction): Listing local files at directory '/Users/usr0101931/devel/psql-test/csv' filtering filename by prefix 'sample_'
2015-07-02 18:45:17.254 +0900 [INFO] (transaction): Loading files []
2015-07-02 18:45:17.415 +0900 [INFO] (transaction): Connecting to jdbc:postgresql://localhost:5432/psql_test options {user=usr0101931, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2015-07-02 18:45:17.542 +0900 [INFO] (transaction): SQL: SET search_path TO "public"
2015-07-02 18:45:17.546 +0900 [INFO] (transaction): > 0.00 seconds
2015-07-02 18:45:17.547 +0900 [INFO] (transaction): Using insert mode
2015-07-02 18:45:17.724 +0900 [INFO] (transaction): Connecting to jdbc:postgresql://localhost:5432/psql_test options {user=usr0101931, tcpKeepAlive=true, loginTimeout=300, socketTimeout=28800}
2015-07-02 18:45:17.739 +0900 [INFO] (transaction): SQL: SET search_path TO "public"
2015-07-02 18:45:17.740 +0900 [INFO] (transaction): > 0.00 seconds
2015-07-02 18:45:17.741 +0900 [INFO] (transaction): SQL: INSERT INTO "sample" ("id", "account", "time", "purchase", "comment")
2015-07-02 18:45:17.757 +0900 [ERROR] (transaction): Operation failed (0:42601)
java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  ポジション: 71
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.commit(org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java:355)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.transaction(org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java:292)
	at org.embulk.exec.BulkLoader$4$1$1.transaction(org/embulk/exec/BulkLoader.java:493)
	at org.embulk.exec.LocalExecutorPlugin.transaction(org/embulk/exec/LocalExecutorPlugin.java:37)
	at org.embulk.exec.BulkLoader$4$1.run(org/embulk/exec/BulkLoader.java:489)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(org/embulk/spi/util/Filters.java:97)
	at org.embulk.spi.util.Filters.transaction(org/embulk/spi/util/Filters.java:50)
	at org.embulk.exec.BulkLoader$4.run(org/embulk/exec/BulkLoader.java:484)
	at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(org/embulk/spi/FileInputRunner.java:117)
	at org.embulk.standards.CsvParserPlugin.transaction(org/embulk/standards/CsvParserPlugin.java:121)
	at org.embulk.spi.FileInputRunner$RunnerControl$1.run(org/embulk/spi/FileInputRunner.java:111)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(org/embulk/spi/util/Decoders.java:77)
	at org.embulk.spi.util.Decoders$RecursiveControl$1.run(org/embulk/spi/util/Decoders.java:73)
	at org.embulk.standards.GzipFileDecoderPlugin.transaction(org/embulk/standards/GzipFileDecoderPlugin.java:30)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(org/embulk/spi/util/Decoders.java:68)
	at org.embulk.spi.util.Decoders.transaction(org/embulk/spi/util/Decoders.java:33)
	at org.embulk.spi.FileInputRunner$RunnerControl.run(org/embulk/spi/FileInputRunner.java:108)
	at org.embulk.standards.LocalFileInputPlugin.resume(org/embulk/standards/LocalFileInputPlugin.java:80)
	at org.embulk.standards.LocalFileInputPlugin.transaction(org/embulk/standards/LocalFileInputPlugin.java:70)
	at org.embulk.spi.FileInputRunner.transaction(org/embulk/spi/FileInputRunner.java:63)
	at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:480)
	at org.embulk.exec.BulkLoader.access$100(org/embulk/exec/BulkLoader.java:36)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:342)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:338)
	at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:24)
	at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:338)
	at org.embulk.command.Runner.run(org/embulk/command/Runner.java:149)
	at org.embulk.command.Runner.main(org/embulk/command/Runner.java:101)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:497)
	at RUBY.run(file:/Users/usr0101931/.embulk/bin/embulk!/embulk/command/embulk_run.rb:351)
	at classpath_3a_embulk.command.embulk.(root)(classpath:embulk/command/embulk.rb:47)
	at classpath_3a_embulk.command.embulk.(root)(classpath_3a_embulk/command/classpath:embulk/command/embulk.rb:47)
	at org.embulk.cli.Main.main(org/embulk/cli/Main.java:11)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  ポジション: 71
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:406)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:334)
	at org.embulk.output.jdbc.JdbcOutputConnection.executeUpdate(JdbcOutputConnection.java:460)
	at org.embulk.output.jdbc.JdbcOutputConnection.collectInsert(JdbcOutputConnection.java:279)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.doCommit(AbstractJdbcOutputPlugin.java:588)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$2.run(AbstractJdbcOutputPlugin.java:348)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$8.call(AbstractJdbcOutputPlugin.java:892)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$8.call(AbstractJdbcOutputPlugin.java:889)
	at org.embulk.spi.util.RetryExecutor.run(RetryExecutor.java:100)
	at org.embulk.spi.util.RetryExecutor.runInterruptible(RetryExecutor.java:77)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.withRetry(AbstractJdbcOutputPlugin.java:885)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.withRetry(AbstractJdbcOutputPlugin.java:878)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.commit(AbstractJdbcOutputPlugin.java:343)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.transaction(AbstractJdbcOutputPlugin.java:292)
	at org.embulk.exec.BulkLoader$4$1$1.transaction(BulkLoader.java:493)
	at org.embulk.exec.LocalExecutorPlugin.transaction(LocalExecutorPlugin.java:37)
	at org.embulk.exec.BulkLoader$4$1.run(BulkLoader.java:489)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:97)
	at org.embulk.spi.util.Filters.transaction(Filters.java:50)
	at org.embulk.exec.BulkLoader$4.run(BulkLoader.java:484)
	at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(FileInputRunner.java:117)
	at org.embulk.standards.CsvParserPlugin.transaction(CsvParserPlugin.java:121)
	at org.embulk.spi.FileInputRunner$RunnerControl$1.run(FileInputRunner.java:111)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:77)
	at org.embulk.spi.util.Decoders$RecursiveControl$1.run(Decoders.java:73)
	at org.embulk.standards.GzipFileDecoderPlugin.transaction(GzipFileDecoderPlugin.java:30)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:68)
	at org.embulk.spi.util.Decoders.transaction(Decoders.java:33)
	at org.embulk.spi.FileInputRunner$RunnerControl.run(FileInputRunner.java:108)
	at org.embulk.standards.LocalFileInputPlugin.resume(LocalFileInputPlugin.java:80)
	at org.embulk.standards.LocalFileInputPlugin.transaction(LocalFileInputPlugin.java:70)
	at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:63)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:480)
	at org.embulk.exec.BulkLoader.access$100(BulkLoader.java:36)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:342)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:338)
	at org.embulk.spi.Exec.doWith(Exec.java:24)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:338)
	at org.embulk.command.Runner.run(Runner.java:149)
	at org.embulk.command.Runner.main(Runner.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:470)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:328)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:71)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
	at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
	at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
	at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.CaseNode.interpret(CaseNode.java:138)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
	at classpath_3a_embulk.command.embulk.__file__(classpath:embulk/command/embulk.rb:47)
	at classpath_3a_embulk.command.embulk.load(classpath:embulk/command/embulk.rb)
	at org.jruby.Ruby.runScript(Ruby.java:866)
	at org.jruby.Ruby.runScript(Ruby.java:859)
	at org.jruby.Ruby.runNormally(Ruby.java:728)
	at org.jruby.Ruby.runFromMain(Ruby.java:577)
	at org.jruby.Main.doRunFromMain(Main.java:395)
	at org.jruby.Main.internalRun(Main.java:290)
	at org.jruby.Main.run(Main.java:217)
	at org.jruby.Main.main(Main.java:197)
	at org.embulk.cli.Main.main(Main.java:11)

Error: org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  ポジション: 71
```

The reason of the exception is invalid INSERT INTO statement.

```
2015-07-02 18:45:17.741 +0900 [INFO] (transaction): SQL: INSERT INTO "sample" ("id", "account", "time", "purchase", "comment")
```

I could avoid the exception by inserting the following codes at the top of doCommit method of AbstractJdbcOutputPlugin class. However, I don't know whether this modification is OK or not for REPLACE option.

```
    protected void doCommit(JdbcOutputConnection con, PluginTask task, int taskCount)
        throws SQLException
    {
        if (task.getIntermediateTables().get().size() == 0) {
            return;
        }
```

**Comment by hito4t** [comment]
Thank you for your report.

As you wrote, INSERT mode, TRUNCATE_INSERT mode and MERGE mode fail if no input file exists.
(`doCommit` method isn't called in INSERT_DIRECT mode and MERGE_DIRECT mode, and the size of `intermediateTables` is always 1 in REPLACE mode.)

I'll merge your code above.

**Comment by muziyoshiz** [comment]
Thank you very much!
I confirmed that embulk-output-jdbc 0.4.1 solved the above problem in my environment.
