### ISSUE TITLE
when load data to oracle ，it raise table not exists error while it actually exists

### ISSUE THREAD

**Issue by yester354** [embulk/embulk-output-jdbc#57]
i am try to load data from oracle to oracle in deferent machine.i tried to delete ~/.embulk/jruby* directories and reinstalled embulk-input-oracle.it works .now i encounter another program.
i configure .yml file as below

in:
type: oracle
driver_path: /oracle/11.2.4/jdbc/lib/ojdbc6.jar
host: 10.89.13.56
user: sync
password: m123
database: desync
query: |
select * from sync.test
out: {type: oracle, driver_path: /oracle/11.2.4/jdbc/lib/ojdbc6.jar, host: 10.89.13.57,
user: flume, password: m123, database: flume, table: test, mode: insert, insert_method: normal}

host 10.89.13.56
SQL> select * from sync.test;

COL

a

SQL> 
host 10.89.13.57
SQL> select * from flume.test
2 ;

no rows selected

SQL>

when i run embulk run. it raise error as below 
root@localhost embulk-master]# embulk run newl.yml
2015-08-23 13:27:14.000 +0800: Embulk v0.7.2
2015-08-23 13:27:16.089 +0800 INFO: Loaded plugin embulk-input-oracle (0.6.0)
2015-08-23 13:27:16.124 +0800 INFO: Loaded plugin embulk-output-oracle (0.4.1)
2015-08-23 13:27:16.745 +0800 INFO: Connecting to jdbc:oracle:thin:@10.89.13.57:1521:flume options {user=flume}
2015-08-23 13:27:17.027 +0800 INFO: Using insert mode
2015-08-23 13:27:17.086 +0800 INFO: SQL: CREATE TABLE "test_5d959b400d59f80_bl_tmp000" ("COL" CLOB)
2015-08-23 13:27:17.103 +0800 INFO: > 0.02 seconds
2015-08-23 13:27:17.147 +0800 INFO: {done: 0 / 1, running: 0}
2015-08-23 13:27:17.194 +0800 INFO: Connecting to jdbc:oracle:thin:@10.89.13.57:1521:flume options {user=flume}
2015-08-23 13:27:17.198 +0800 INFO: Connecting to jdbc:oracle:thin:@10.89.13.57:1521:flume options {user=flume}
2015-08-23 13:27:17.239 +0800 INFO: Prepared SQL: INSERT INTO "test_5d959b400d59f80_bl_tmp000" ("COL") VALUES (?)
2015-08-23 13:27:17.242 +0800 WARN: An output plugin is compiled with old Embulk plugin API. Please update the plugin version using "embulk gem install" command, or contact a developer of the plugin to upgrade the plugin code using "embulk migrate" command: class org.embulk.output.jdbc.AbstractJdbcOutputPlugin$PluginPageOutput
2015-08-23 13:27:17.326 +0800 INFO: SQL: select * from sync.test

2015-08-23 13:27:17.337 +0800 INFO: > 0.01 seconds
2015-08-23 13:27:17.346 +0800 INFO: Loading 1 rows
2015-08-23 13:27:17.388 +0800 INFO: > 0.04 seconds (loaded 1 rows in total)
2015-08-23 13:27:17.389 +0800 INFO: {done: 1 / 1, running: 0}
2015-08-23 13:27:17.389 +0800 INFO: Connecting to jdbc:oracle:thin:@10.89.13.57:1521:flume options {user=flume}
2015-08-23 13:27:17.419 +0800 INFO: SQL: INSERT INTO "test" ("COL") SELECT "COL" FROM "test_5d959b400d59f80_bl_tmp000"
2015-08-23 13:27:17.427 +0800 ERROR: Operation failed (942:42000)
2015-08-23 13:27:17.436 +0800 INFO: Connecting to jdbc:oracle:thin:@10.89.13.57:1521:flume options {user=flume}
2015-08-23 13:27:17.466 +0800 INFO: SQL: DROP TABLE "test_5d959b400d59f80_bl_tmp000"
2015-08-23 13:27:17.505 +0800 INFO: > 0.04 seconds
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

    at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:328)
    at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:526)
    at org.embulk.exec.BulkLoader.access$100(org/embulk/exec/BulkLoader.java:33)
    at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:339)
    at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:335)
    at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
    at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:335)
    at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:179)
    at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
    at RUBY.run(/root/.embulk/bin/embulk!/embulk/runner.rb:77)
    at RUBY.run(/root/.embulk/bin/embulk!/embulk/command/embulk_run.rb:274)
    at RUBY.<top>(/root/.embulk/bin/embulk!/embulk/command/embulk_main.rb:2)
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:940)
    at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
    at root.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.<top>(file:/root/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:55)
    at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:599)
    at org.embulk.cli.Main.main(org/embulk/cli/Main.java:20)
Caused by: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

    at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.commit(AbstractJdbcOutputPlugin.java:352)
    at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.transaction(AbstractJdbcOutputPlugin.java:289)
    at org.embulk.exec.BulkLoader$4$1$1.transaction(BulkLoader.java:490)
    at org.embulk.exec.LocalExecutorPlugin.transaction(LocalExecutorPlugin.java:36)
    at org.embulk.exec.BulkLoader$4$1.run(BulkLoader.java:486)
    at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:96)
    at org.embulk.spi.util.Filters.transaction(Filters.java:49)
    at org.embulk.exec.BulkLoader$4.run(BulkLoader.java:481)
    at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:147)
    at org.embulk.plugin.compat.InputPluginWrapper.transaction(InputPluginWrapper.java:57)
    at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:477)
    at org.embulk.exec.BulkLoader.access$100(BulkLoader.java:33)
    at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:339)
    at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:335)
    at org.embulk.spi.Exec.doWith(Exec.java:25)
    at org.embulk.exec.BulkLoader.run(BulkLoader.java:335)
    at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:457)
    at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:318)
    at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:45)
    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
    at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:289)
    at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
    at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
    at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:114)
    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
    at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
    at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
    at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:321)
    at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
    at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:82)
    at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:198)
    at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:184)
    at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:201)
    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
    at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:289)
    at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
    at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:116)
    at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:103)
    at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:32)
    at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
    at org.jruby.Ruby.runInterpreter(Ruby.java:837)
    at org.jruby.Ruby.loadFile(Ruby.java:2901)
    at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:245)
    at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:35)
    at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:895)
    at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:540)
    at org.jruby.runtime.load.LoadService.requireCommon(LoadService.java:425)
    at org.jruby.runtime.load.LoadService.require(LoadService.java:391)
    at org.jruby.RubyKernel.requireCommon(RubyKernel.java:947)
    at org.jruby.RubyKernel.require19(RubyKernel.java:940)
    at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
    at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:364)
    at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
    at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:289)
    at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
    at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:82)
    at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:198)
    at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:184)
    at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:201)
    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
    at root.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther74:require(file:/root/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb)
    at root.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.RUBY$script(file:/root/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:55)
    at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:599)
    at org.jruby.ir.Compiler$1.load(Compiler.java:111)
    at org.jruby.Ruby.runScript(Ruby.java:821)
    at org.jruby.Ruby.runScript(Ruby.java:813)
    at org.jruby.Ruby.runNormally(Ruby.java:751)
    at org.jruby.Ruby.runFromMain(Ruby.java:573)
    at org.jruby.Main.doRunFromMain(Main.java:403)
    at org.jruby.Main.internalRun(Main.java:298)
    at org.jruby.Main.run(Main.java:225)
    at org.jruby.Main.main(Main.java:197)
    at org.embulk.cli.Main.main(Main.java:20)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
    at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
    at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
    at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
    at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
    at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:195)
    at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1036)
    at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336)
    at oracle.jdbc.driver.OracleStatement.executeUpdateInternal(OracleStatement.java:1845)
    at oracle.jdbc.driver.OracleStatement.executeUpdate(OracleStatement.java:1810)
    at oracle.jdbc.driver.OracleStatementWrapper.executeUpdate(OracleStatementWrapper.java:294)
    at org.embulk.output.jdbc.JdbcOutputConnection.executeUpdate(JdbcOutputConnection.java:460)
    at org.embulk.output.jdbc.JdbcOutputConnection.collectInsert(JdbcOutputConnection.java:279)
    at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.doCommit(AbstractJdbcOutputPlugin.java:592)
    at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$2.run(AbstractJdbcOutputPlugin.java:345)
    at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$8.call(AbstractJdbcOutputPlugin.java:901)
    at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$8.call(AbstractJdbcOutputPlugin.java:898)
    at org.embulk.spi.util.RetryExecutor.run(RetryExecutor.java:100)
    at org.embulk.spi.util.RetryExecutor.runInterruptible(RetryExecutor.java:77)
    at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.withRetry(AbstractJdbcOutputPlugin.java:894)
    at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.withRetry(AbstractJdbcOutputPlugin.java:887)
    at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.commit(AbstractJdbcOutputPlugin.java:340)
    ... 83 more
Error: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

i don't know why it report table or view does not exist.because in both oracle database .the test table exists actually
thanks for you replay

**Comment by hito4t** [comment]
Hi
embulk-output-oracle adds double quotations to the table name when building SQL (`test` -> `"test"`).
Namely, the table name in yml is case-sensitive.

If `TEST` table exists but `test` table doesn't exist, embulk-output-oracle cannot find the `test` table.
Can you check the exact table name?
(ex. `select table_name from user_tables where lower(table_name) = 'test'`)

We should note to the document of embulk-output-oracle.

Thanks

**Comment by yester354** [comment]
@hito4t 
 Hi  my ploblem is actaully what you said .now it work well.thank you very much

**Comment by hito4t** [comment]
I'm happy your embulk works!
