### ISSUE TITLE
when loading data to oracle and the target table has  a column include '()' .it raise error 

### ISSUE THREAD

**Issue by yester354** [embulk/embulk-output-jdbc#58]
Hi
    I encounter a problem when  loading data to oracle and the target table has  a column include "()"

table test:
SQL> desc sync.test1
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 COL                                                VARCHAR2(32)

SQL> 

if i execute embulk run. it will raise error as below 

[root@localhost embulk-master]# embulk run a.yml
2015-08-24 10:43:57.549 +0800: Embulk v0.7.2
2015-08-24 10:43:59.720 +0800 [INFO] (transaction): Loaded plugin embulk-input-oracle (0.6.0)
2015-08-24 10:43:59.755 +0800 [INFO] (transaction): Loaded plugin embulk-output-oracle (0.4.1)
2015-08-24 10:44:00.407 +0800 [INFO] (transaction): Connecting to jdbc:oracle:thin:@10.89.13.57:1521:flume options {user=flume}
2015-08-24 10:44:00.694 +0800 [INFO] (transaction): Using insert mode
2015-08-24 10:44:00.758 +0800 [INFO] (transaction): SQL: CREATE TABLE "TEST1_da84ef265366c0_bl_tmp000" ("COL" VARCHAR2)
2015-08-24 10:44:00.765 +0800 [ERROR] (transaction): Operation failed (906:42000)
java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: ORA-00906: missing left parenthesis

        at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.begin(org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java:330)
        at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.transaction(org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java:287)
        at org.embulk.exec.BulkLoader$4$1$1.transaction(org/embulk/exec/BulkLoader.java:490)
        at org.embulk.exec.LocalExecutorPlugin.transaction(org/embulk/exec/LocalExecutorPlugin.java:36)
        at org.embulk.exec.BulkLoader$4$1.run(org/embulk/exec/BulkLoader.java:486)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(org/embulk/spi/util/Filters.java:96)
        at org.embulk.spi.util.Filters.transaction(org/embulk/spi/util/Filters.java:49)
        at org.embulk.exec.BulkLoader$4.run(org/embulk/exec/BulkLoader.java:481)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(org/embulk/input/jdbc/AbstractJdbcInputPlugin.java:147)
        at org.embulk.plugin.compat.InputPluginWrapper.transaction(org/embulk/plugin/compat/InputPluginWrapper.java:57)
        at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:477)
        at org.embulk.exec.BulkLoader.access$100(org/embulk/exec/BulkLoader.java:33)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:339)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:335)
        at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
        at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:335)
        at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:179)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
        at RUBY.run(/root/.embulk/bin/embulk!/embulk/runner.rb:77)
        at RUBY.run(/root/.embulk/bin/embulk!/embulk/command/embulk_run.rb:274)
        at RUBY.<top>(/root/.embulk/bin/embulk!/embulk/command/embulk_main.rb:2)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:940)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
        at root.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.<top>(file:/root/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:55)
        at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:599)
        at org.embulk.cli.Main.main(org/embulk/cli/Main.java:20)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00906: missing left parenthesis

        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:195)
        at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1036)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336)
        at oracle.jdbc.driver.OracleStatement.executeUpdateInternal(OracleStatement.java:1845)
        at oracle.jdbc.driver.OracleStatement.executeUpdate(OracleStatement.java:1810)
        at oracle.jdbc.driver.OracleStatementWrapper.executeUpdate(OracleStatementWrapper.java:294)
        at org.embulk.output.jdbc.JdbcOutputConnection.executeUpdate(JdbcOutputConnection.java:460)
        at org.embulk.output.oracle.OracleOutputConnection.createTable(OracleOutputConnection.java:86)
        at org.embulk.output.oracle.OracleOutputConnection.createTableIfNotExists(OracleOutputConnection.java:77)
        at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.doBegin(AbstractJdbcOutputPlugin.java:427)
        at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$1.run(AbstractJdbcOutputPlugin.java:323)
        at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$8.call(AbstractJdbcOutputPlugin.java:901)
        at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$8.call(AbstractJdbcOutputPlugin.java:898)
        at org.embulk.spi.util.RetryExecutor.run(RetryExecutor.java:100)
        at org.embulk.spi.util.RetryExecutor.runInterruptible(RetryExecutor.java:77)
        at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.withRetry(AbstractJdbcOutputPlugin.java:894)
        at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.withRetry(AbstractJdbcOutputPlugin.java:887)
        at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.begin(AbstractJdbcOutputPlugin.java:318)
        at org.embulk.output.jdbc.AbstractJdbcOutputPlugin.transaction(AbstractJdbcOutputPlugin.java:287)
        at org.embulk.exec.BulkLoader$4$1$1.transaction(BulkLoader.java:490)
        at org.embulk.exec.LocalExecutorPlugin.transaction(LocalExecutorPlugin.java:36)
        at org.embulk.exec.BulkLoader$4$1.run(BulkLoader.java:486)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:96)
        at org.embulk.spi.util.Filters.transaction(Filters.java:49)
        at org.embulk.exec.BulkLoader$4.run(BulkLoader.java:481)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:147)
        at org.embulk.plugin.compat.InputPluginWrapper.transaction(InputPluginWrapper.java:57)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:477)
        at org.embulk.exec.BulkLoader.access$100(BulkLoader.java:33)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:339)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:335)
        at org.embulk.spi.Exec.doWith(Exec.java:25)
        at org.embulk.exec.BulkLoader.run(BulkLoader.java:335)
        at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:179)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:457)
        at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:318)
        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:45)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:289)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:128)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:114)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
        at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:321)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:82)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:198)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:184)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:201)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:289)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:116)
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:103)
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:32)
        at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
        at org.jruby.Ruby.runInterpreter(Ruby.java:837)
        at org.jruby.Ruby.loadFile(Ruby.java:2901)
        at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:245)
        at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:35)
        at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:895)
        at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:540)
        at org.jruby.runtime.load.LoadService.requireCommon(LoadService.java:425)
        at org.jruby.runtime.load.LoadService.require(LoadService.java:391)
        at org.jruby.RubyKernel.requireCommon(RubyKernel.java:947)
        at org.jruby.RubyKernel.require19(RubyKernel.java:940)
        at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:364)
        at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:289)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:82)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:198)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:184)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:201)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
        at root.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther74:require(file:/root/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb)
        at root.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.RUBY$script(file:/root/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:55)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:599)
        at org.jruby.ir.Compiler$1.load(Compiler.java:111)
        at org.jruby.Ruby.runScript(Ruby.java:821)
        at org.jruby.Ruby.runScript(Ruby.java:813)
        at org.jruby.Ruby.runNormally(Ruby.java:751)
        at org.jruby.Ruby.runFromMain(Ruby.java:573)
        at org.jruby.Main.doRunFromMain(Main.java:403)
        at org.jruby.Main.internalRun(Main.java:298)
        at org.jruby.Main.run(Main.java:225)
        at org.jruby.Main.main(Main.java:197)
        at org.embulk.cli.Main.main(Main.java:20)

Error: java.sql.SQLSyntaxErrorException: ORA-00906: missing left parenthesis

in the content  of the error.it failed to execute "CREATE TABLE "TEST1_da84ef265366c0_bl_tmp000" ("COL" VARCHAR2)" . and it lack "(32)" .how to modify the .yml file to handle this problem
thanks for you replay

**Comment by hito4t** [comment]
Hi
You can specify column types in SQL for creating temporary table as following.
<pre>
out:
    type: oracle
    ...
    column_options:
      COL: {type: VARCHAR2(32)}
</pre>

embulk-output-oracle will fix this problem in future.

Thanks

**Comment by yester354** [comment]
@hito4t 
Hi it works .thank you very much
