### ISSUE TITLE
Redshift - Unable to unmarshall error response (null)

### ISSUE THREAD

**Issue by daledude** [embulk/embulk-output-jdbc#63]
I get the below stack trace after an import. The csv file is copied to my S3 bucket and the Redshift temp table is created and dropped properly but no data is in the final table. I'm using mode: insert.

If I run the COPY FROM command manually it succeeds.

Dunno if this WARN is related:
```
2015-09-03 05:41:28.752 -0700 [WARN] (task-0000): An output plugin is compiled with old Embulk plugin API. Please update the plugin version using "embulk gem install" command, or contact a developer of the plugin to upgrade the plugin code using "embulk migrate" command: class org.embulk.output.jdbc.AbstractJdbcOutputPlugin$PluginPageOutput
```

```
org.embulk.exec.PartialExecutionException: com.amazonaws.AmazonClientException: Unable to unmarshall error response (null). Response Code: 403, Response Text: Forbidden
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:328)
	at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:526)
	at org.embulk.exec.BulkLoader.access$100(org/embulk/exec/BulkLoader.java:33)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:339)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:335)
	at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
	at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:335)
	at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:179)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
	at RUBY.run(/home/dude/.embulk/bin/embulk!/embulk/runner.rb:77)
	at RUBY.run(/home/dude/.embulk/bin/embulk!/embulk/command/embulk_run.rb:278)
	at RUBY.<top>(/home/dude/.embulk/bin/embulk!/embulk/command/embulk_main.rb:2)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:940)
	at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
	at home.dude.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.<top>(file:/home/dude/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:55)
	at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:599)
	at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
Caused by: com.amazonaws.AmazonClientException: Unable to unmarshall error response (null). Response Code: 403, Response Text: Forbidden
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1071)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:725)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1091)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.getFederationToken(AWSSecurityTokenServiceClient.java:829)
	at org.embulk.output.redshift.RedshiftCopyBatchInsert.generateReaderSessionCredentials(RedshiftCopyBatchInsert.java:135)
	at org.embulk.output.redshift.RedshiftCopyBatchInsert.access$400(RedshiftCopyBatchInsert.java:30)
	at org.embulk.output.redshift.RedshiftCopyBatchInsert$UploadAndCopyTask.call(RedshiftCopyBatchInsert.java:169)
	at org.embulk.output.redshift.RedshiftCopyBatchInsert.flush(RedshiftCopyBatchInsert.java:90)
	at org.embulk.output.postgresql.AbstractPostgreSQLCopyBatchInsert.finish(AbstractPostgreSQLCopyBatchInsert.java:81)
	at org.embulk.output.redshift.RedshiftCopyBatchInsert.finish(RedshiftCopyBatchInsert.java:104)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$PluginPageOutput.finish(AbstractJdbcOutputPlugin.java:843)
	at org.embulk.plugin.compat.TransactionalPageOutputWrapper.finish(TransactionalPageOutputWrapper.java:62)
	at org.embulk.spi.PageBuilder.finish(PageBuilder.java:223)
	at org.embulk.standards.CsvParserPlugin.run(CsvParserPlugin.java:376)
	at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:147)
	at org.embulk.spi.util.Executors.process(Executors.java:61)
	at org.embulk.spi.util.Executors.process(Executors.java:40)
	at org.embulk.exec.LocalExecutorPlugin$2.call(LocalExecutorPlugin.java:104)
	at org.embulk.exec.LocalExecutorPlugin$2.call(LocalExecutorPlugin.java:100)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at javax.xml.xpath.XPathFactoryFinder._newFactory(XPathFactoryFinder.java:220)
	at javax.xml.xpath.XPathFactoryFinder.newFactory(XPathFactoryFinder.java:141)
	at javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:182)
	at javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:96)
	at com.amazonaws.util.XpathUtils.xpath(XpathUtils.java:114)
	at com.amazonaws.util.XpathUtils.asString(XpathUtils.java:197)
	at com.amazonaws.transform.StandardErrorUnmarshaller.parseErrorCode(StandardErrorUnmarshaller.java:93)
	at com.amazonaws.services.securitytoken.model.transform.ExpiredTokenExceptionUnmarshaller.unmarshall(ExpiredTokenExceptionUnmarshaller.java:34)
	at com.amazonaws.services.securitytoken.model.transform.ExpiredTokenExceptionUnmarshaller.unmarshall(ExpiredTokenExceptionUnmarshaller.java:25)
	at com.amazonaws.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:95)
	at com.amazonaws.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:40)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1045)
	... 24 more

Error: com.amazonaws.AmazonClientException: Unable to unmarshall error response (null). Response Code: 403, Response Text: Forbidden

```

**Comment by hito4t** [comment]
Hi
It seems `AWSSecurityTokenServiceClient.getFederationToken` failed.
Does the IAM user have `sts:GetFederationToken` permission?.

**Comment by daledude** [comment]
Hi @hito4t 

That was the trick. Thanks much!
