### ISSUE TITLE
Redshift S3 permissions more complex than needed

### ISSUE THREAD

**Issue by lance-edmodo** [embulk/embulk-output-jdbc#85]
I could not get the STS Federated session key feature to work, so I added an option to just use the given S3 access&secret keys.

We do not use this feature at all in our (large) AWS deployment, and our very competent security people don't think it's all that useful. I'll post a pull request when I have time.

**Comment by hito4t** [comment]
Thank you for your comment.

We are expecting the pull request.

> I could not get the STS Federated session key feature to work

Does that mean embulk threw an exception?
If so, can you paste the stack trace?

Thanks

**Comment by lance-edmodo** [comment]
https://github.com/embulk/embulk-output-jdbc/pull/86

**Comment by lance-edmodo** [comment]
My user had full permissions in S3 and STS. We don't use temporary credentials in our site. I was not able to debug making it useable.

Here is the stack trace:

  -----------------------------------------------
  error:  S3ServiceException:Access Denied,Status 403,Error AccessDenied,Rid deadbeef,ExtRid deadbeef=,CanRetry 1
  code:      8001
  context:   S3 key being read : s3://big_big_bucket/tmp/json_test2/3138c507-e4d9-4988-b7b2-0753589d5464
  query:     672099
  location:  table_s3_scanner.cpp:354
  process:   query3_45 [pid=3404]
  -----------------------------------------------

	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:363)
	at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:572)
	at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:374)
	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:370)
	at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
	at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:370)
	at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:180)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
	at RUBY.run(/home/lance/.embulk/bin/embulk!/embulk/runner.rb:77)
	at RUBY.run(/home/lance/.embulk/bin/embulk!/embulk/command/embulk_run.rb:296)
	at RUBY.<top>(/home/lance/.embulk/bin/embulk!/embulk/command/embulk_main.rb:2)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:939)
	at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
	at home.lance.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.<top>(file:/home/lance/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:599)
	at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
Caused by: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: S3ServiceException:Access Denied,Status 403,Error AccessDenied,Rid deadbeef,ExtRid deadbeef=,CanRetry 1
  Detail: 
  -----------------------------------------------
  error:  S3ServiceException:Access Denied,Status 403,Error AccessDenied,Rid deadbeef,ExtRid deadbeef=,CanRetry 1
  code:      8001
  context:   S3 key being read : s3://big_big_bucket/tmp/json_test2/3138c507-e4d9-4988-b7b2-0753589d5464
  query:     672099
  location:  table_s3_scanner.cpp:354
  process:   query3_45 [pid=3404]
  -----------------------------------------------

	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$PluginPageOutput.finish(AbstractJdbcOutputPlugin.java:910)
	at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput.finish(LocalExecutorPlugin.java:474)
	at org.embulk.spi.PageBuilder.finish(PageBuilder.java:244)
	at org.embulk.input.jdbc.AbstractJdbcInputPlugin.run(AbstractJdbcInputPlugin.java:266)
	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:294)
	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$000(LocalExecutorPlugin.java:212)
	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:257)
	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:253)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERROR: S3ServiceException:Access Denied,Status 403,Error AccessDenied,Rid deadbeef,ExtRid deadbeef=,CanRetry 1
  Detail: 
  -----------------------------------------------
  error:  S3ServiceException:Access Denied,Status 403,Error AccessDenied,Rid deadbeef,ExtRid deadbeef=,CanRetry 1
  code:      8001
  context:   S3 key being read : s3://big_big_bucket/tmp/json_test2/3138c507-e4d9-4988-b7b2-0753589d5464
  query:     672099
  location:  table_s3_scanner.cpp:354
  process:   query3_45 [pid=3404]
  -----------------------------------------------

	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:481)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:409)
	at org.embulk.output.redshift.RedshiftOutputConnection.runCopy(RedshiftOutputConnection.java:119)
	at org.embulk.output.redshift.RedshiftCopyBatchInsert$UploadAndCopyTask.call(RedshiftCopyBatchInsert.java:181)
	at org.embulk.output.redshift.RedshiftCopyBatchInsert.flush(RedshiftCopyBatchInsert.java:92)
	at org.embulk.output.postgresql.AbstractPostgreSQLCopyBatchInsert.finish(AbstractPostgreSQLCopyBatchInsert.java:78)
	at org.embulk.output.redshift.RedshiftCopyBatchInsert.finish(RedshiftCopyBatchInsert.java:106)
	at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$PluginPageOutput.finish(AbstractJdbcOutputPlugin.java:908)
	... 11 more

Error: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: S3ServiceException:Access Denied,Status 403,Error AccessDenied,Rid deadbeef,ExtRid deadbeef=,CanRetry 1
  Detail: 
  -----------------------------------------------
  error:  S3ServiceException:Access Denied,Status 403,Error AccessDenied,Rid deadbeef,ExtRid deadbeef=,CanRetry 1
  code:      8001
  context:   S3 key being read : s3://big_big_bucket/tmp/json_test2/3138c507-e4d9-4988-b7b2-0753589d5464
  query:     672099
  location:  table_s3_scanner.cpp:354
  process:   query3_45 [pid=3404]
  -----------------------------------------------

**Comment by lance-edmodo** [comment]
The Pull Request is finished: https://github.com/embulk/embulk-output-jdbc/pull/86 .

**Comment by lance-edmodo** [comment]
Ok, I've cleaned it up as much as I can. Please review https://github.com/embulk/embulk-output-jdbc/pull/86/files .

Thanks!

**Comment by hito4t** [comment]
#86 has been merged.
